#ifndef HEAD_H
#define HEAD_H
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <pthread.h>
#include <string.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <stdbool.h>
#include <pwd.h>
#include <sys/wait.h>
#include <signal.h>
#include <pthread.h>
#include <poll.h>
#include <sys/select.h>
#include <sys/errno.h>
#include <sys/epoll.h>
#include "./global.h"
#include "./common.h"
#include "./color.h"
#include "./datatype.h"
#include <curses.h>
#include <sys/time.h>
#include "./show_strength.h"
#include "./show_data_stream.h"
#include "./ball_status.h"
#include <locale.h>
#include <cjson/cJSON.h>
#endif
